apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: weather-app-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: weather-app
        version: v1
    spec:
      containers:
      - name: weatherappcontainer
        image: stackupiss/weather:v1
        imagePullPolicy: Always
        env:
          - name: APP_ID
            value: 3af4185f06b6f8d839b72273c3d006f4
          - name: DEFAULT_CITY
            value: Singapore
        ports:
          - containerPort: 6000