# Default values for demopythonapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
productionReplicaCount: 2

image:
  repository: balanus/weatherapp
  tag: fixedv1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

version: v1

deployment:
  containerPort: 3000

APP_ID: ecbd92ff90840c3a36dad8d16f7f7fb2
APP_DEFAULT_CITY: Singapore

productionEnv: true